# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ruidong/agent/v1/events.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ruidong/agent/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1druidong/agent/v1/events.proto\x12\x10ruidong.agent.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xf4\x01\n\nAgentEvent\x12\x0b\n\x03seq\x18\x01 \x01(\x03\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12\x0e\n\x06run_id\x18\x03 \x01(\t\x12\x0f\n\x07turn_id\x18\x04 \x01(\t\x12\x12\n\nevent_type\x18\x05 \x01(\t\x12(\n\x07payload\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x16\n\x0eschema_version\x18\x07 \x01(\t\x12\x17\n\nmessage_id\x18\x08 \x01(\tH\x00\x88\x01\x01\x12\x16\n\taction_id\x18\t \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_message_idB\x0c\n\n_action_id*\xb7\x03\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x45VENT_TYPE_TURN_STARTED\x10\x01\x12\x19\n\x15\x45VENT_TYPE_TEXT_DELTA\x10\x02\x12\x1e\n\x1a\x45VENT_TYPE_REASONING_DELTA\x10\x03\x12 \n\x1c\x45VENT_TYPE_TOOL_CALL_STARTED\x10\x04\x12\x1e\n\x1a\x45VENT_TYPE_TOOL_CALL_DELTA\x10\x05\x12\"\n\x1e\x45VENT_TYPE_TOOL_CALL_COMPLETED\x10\x06\x12 \n\x1c\x45VENT_TYPE_TOOL_CALL_INVALID\x10\x07\x12\x1b\n\x17\x45VENT_TYPE_USAGE_UPDATE\x10\x08\x12\x1b\n\x17\x45VENT_TYPE_TOOL_STARTED\x10\t\x12\x1d\n\x19\x45VENT_TYPE_TOOL_COMPLETED\x10\n\x12\x1a\n\x16\x45VENT_TYPE_TOOL_FAILED\x10\x0b\x12\x1a\n\x16\x45VENT_TYPE_TURN_PAUSED\x10\x0c\x12\x1d\n\x19\x45VENT_TYPE_TURN_COMPLETED\x10\rBPZNgithub.com/shinelee211-arch/ruidong-agent-core/gen/go/ruidong/agent/v1;agentv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ruidong.agent.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNgithub.com/shinelee211-arch/ruidong-agent-core/gen/go/ruidong/agent/v1;agentv1'
  _globals['_EVENTTYPE']._serialized_start=329
  _globals['_EVENTTYPE']._serialized_end=768
  _globals['_AGENTEVENT']._serialized_start=82
  _globals['_AGENTEVENT']._serialized_end=326
# @@protoc_insertion_point(module_scope)
