"""rd-agent-contracts — Agent Runtime PaaS 跨包共享协议。

包含：
- ID 类型与生成器
- Message / ToolCall / ToolResult / AgentEvent 等 dataclass
- EventDraft / EventLogPort append-only 事件日志契约
- AgentRun lifecycle 持久化数据与 port
- ContinuationQueuePort 自动续跑队列契约
- Subagent task/profile、timeline read model、tool execution 契约
- 横切 ports protocol（EventSink / Meter / BudgetGate / PolicyGate /
  CancellationToken / BlobWriter / Clock / IdGenerator）
- __version__：包发版号（跟 pyproject.toml 同步）
- SCHEMA_VERSION：data contract schema 版本，仅在 contract 字段/类型有 breaking change 时 bump
"""

from ._version import SCHEMA_VERSION
from .blob import BlobRef
from .budget import BudgetEnvelope
from .clock import Clock, FrozenClock, SystemClock
from .continuation_queue import (
    ContinuationJobRecord,
    ContinuationJobSpec,
    ContinuationJobStatus,
    ContinuationQueuePort,
)
from .enums import StopReason, ToolCallStatus
from .event_log import EventLogPort
from .events import AgentEvent, EventDraft
from .ids import (
    ActionId,
    IdGenerator,
    MessageId,
    RunId,
    SessionId,
    ToolUseId,
    TurnId,
    UuidIdGenerator,
)
from .managed_agent import (
    ManagedAgentEventReadPort,
    ManagedAgentEventReplay,
    ManagedAgentRecoveryAssessment,
    ManagedAgentRecoveryPort,
)
from .messages import Message, Role, ToolCall, ToolResult
from .ports import (
    BlobWriter,
    BudgetGate,
    CancellationToken,
    EventSink,
    Meter,
    PolicyGate,
)
from .provider_lock import ProviderLock
from .run_persistence import (
    AgentKind,
    RunBudget,
    RunCompletion,
    RunFailure,
    RunPersistencePort,
    RunRecord,
    RunResultMetadata,
    RunScope,
    RunStatus,
)
from .run_policy import (
    CONTINUABLE_STOP_REASONS,
    NEEDS_ATTENTION_STOP_REASONS,
    TERMINAL_WAIT_REASONS,
    completion_status_for_stop_reason,
    is_continuable_stop_reason,
    is_terminal_wait_stop_reason,
    needs_attention_for_stop_reason,
    should_auto_continue_run,
)
from .subagent import (
    BROWSER_TOOLS,
    DIAGNOSTIC_TOOLS,
    READ_ONLY_TOOLS,
    STANDARD_SUBAGENT_PROFILES,
    TASK_TOOLS,
    TERMINAL_SUBAGENT_STATUSES,
    WEB_TOOLS,
    WRITE_TOOLS,
    SubagentProfile,
    SubagentProfileId,
    SubagentRunPort,
    SubagentRunRecord,
    SubagentTaskPort,
    SubagentTaskRecord,
    SubagentTaskSpec,
    SubagentTaskStatus,
    filter_subagent_tools_for_profile,
    find_write_scope_violations,
    is_path_in_write_scope,
    normalize_subagent_profile_id,
    normalize_subagent_scope_path,
    normalize_write_scope_paths,
    resolve_subagent_profile,
    subagent_profile_allows_tool,
    subagent_profile_schema_values,
    validate_subagent_profile_scope,
    write_scopes_overlap,
)
from .subagent_delegation import (
    SubagentDelegationContext,
    SubagentDelegationDecision,
    SubagentDelegationRuleSet,
    decide_subagent_delegation,
)
from .subagent_runtime import (
    MUTATING_TOOLS,
    VERIFIER_VALIDATION_TOOLS,
    SubagentFinalizeDecision,
    SubagentFinalizeOperation,
    SubagentToolHistoryEntry,
    adjusted_subagent_stop_reason_for_profile,
    build_subagent_aggregate_outcome,
    build_subagent_instruction_text,
    build_subagent_outcome_json,
    build_subagent_run_record,
    build_subagent_task_payload,
    decide_subagent_finalization,
    extract_subagent_changed_paths,
    first_failed_tool_error_type,
    format_subagent_aggregate,
    normalize_subagent_tool_history,
    normalize_subagent_tool_history_entry,
)
from .timeline import (
    AgentTimeline,
    TimelineReadPort,
    TimelineRequest,
    TimelineRun,
    TimelineSubagentTask,
)
from .tool_execution import (
    ToolDefinition,
    ToolExecutionContext,
    ToolExecutionRequest,
    ToolExecutionResult,
    ToolExecutorPort,
    ToolObservabilityPort,
    ToolObservabilityRecord,
    ToolRegistryPort,
)
from .trace import CostAttributionTags, LLMCallRecord, TraceContext
from .transcript_blocks import (
    InvalidToolCall,
    ProviderState,
    ReasoningBlock,
    StandardContentBlock,
    StandardToolCall,
    TextBlock,
    ToolUseBlock,
)
from .usage import Usage, normalize_usage
from .workspace import (
    SubagentWorkspaceHandle,
    SubagentWorkspaceIsolationDecision,
    SubagentWorkspaceMergeResult,
    SubagentWorkspacePort,
    SubagentWorkspaceSpec,
    decide_subagent_workspace_isolation,
    should_merge_subagent_workspace,
)

__version__ = "1.14.1"

__all__ = [
    "SCHEMA_VERSION",
    "ActionId",
    "AgentKind",
    "AgentTimeline",
    "AgentEvent",
    "BROWSER_TOOLS",
    "BlobRef",
    "BlobWriter",
    "BudgetEnvelope",
    "BudgetGate",
    "CancellationToken",
    "Clock",
    "CostAttributionTags",
    "ContinuationJobRecord",
    "ContinuationJobSpec",
    "ContinuationJobStatus",
    "ContinuationQueuePort",
    "DIAGNOSTIC_TOOLS",
    "EventDraft",
    "EventLogPort",
    "EventSink",
    "FrozenClock",
    "IdGenerator",
    "InvalidToolCall",
    "Message",
    "MessageId",
    "ManagedAgentEventReadPort",
    "ManagedAgentEventReplay",
    "ManagedAgentRecoveryAssessment",
    "ManagedAgentRecoveryPort",
    "LLMCallRecord",
    "Meter",
    "MUTATING_TOOLS",
    "PolicyGate",
    "ProviderLock",
    "ProviderState",
    "READ_ONLY_TOOLS",
    "ReasoningBlock",
    "Role",
    "RunBudget",
    "RunCompletion",
    "RunFailure",
    "RunId",
    "RunPersistencePort",
    "RunRecord",
    "RunResultMetadata",
    "RunScope",
    "RunStatus",
    "SessionId",
    "StandardContentBlock",
    "StandardToolCall",
    "STANDARD_SUBAGENT_PROFILES",
    "StopReason",
    "SubagentProfile",
    "SubagentProfileId",
    "SubagentFinalizeDecision",
    "SubagentFinalizeOperation",
    "SubagentDelegationContext",
    "SubagentDelegationDecision",
    "SubagentDelegationRuleSet",
    "SubagentRunPort",
    "SubagentRunRecord",
    "SubagentTaskPort",
    "SubagentTaskRecord",
    "SubagentTaskSpec",
    "SubagentTaskStatus",
    "SubagentToolHistoryEntry",
    "SubagentWorkspaceHandle",
    "SubagentWorkspaceIsolationDecision",
    "SubagentWorkspaceMergeResult",
    "SubagentWorkspacePort",
    "SubagentWorkspaceSpec",
    "SystemClock",
    "TASK_TOOLS",
    "TERMINAL_SUBAGENT_STATUSES",
    "TextBlock",
    "TimelineReadPort",
    "TimelineRequest",
    "TimelineRun",
    "TimelineSubagentTask",
    "TraceContext",
    "ToolDefinition",
    "ToolExecutionContext",
    "ToolExecutionRequest",
    "ToolExecutionResult",
    "ToolExecutorPort",
    "ToolObservabilityPort",
    "ToolObservabilityRecord",
    "ToolRegistryPort",
    "ToolCall",
    "ToolCallStatus",
    "ToolResult",
    "ToolUseBlock",
    "ToolUseId",
    "TurnId",
    "Usage",
    "UuidIdGenerator",
    "VERIFIER_VALIDATION_TOOLS",
    "WEB_TOOLS",
    "WRITE_TOOLS",
    "CONTINUABLE_STOP_REASONS",
    "NEEDS_ATTENTION_STOP_REASONS",
    "TERMINAL_WAIT_REASONS",
    "adjusted_subagent_stop_reason_for_profile",
    "build_subagent_aggregate_outcome",
    "build_subagent_instruction_text",
    "build_subagent_outcome_json",
    "build_subagent_run_record",
    "build_subagent_task_payload",
    "completion_status_for_stop_reason",
    "decide_subagent_finalization",
    "decide_subagent_delegation",
    "decide_subagent_workspace_isolation",
    "extract_subagent_changed_paths",
    "filter_subagent_tools_for_profile",
    "first_failed_tool_error_type",
    "find_write_scope_violations",
    "format_subagent_aggregate",
    "is_path_in_write_scope",
    "is_continuable_stop_reason",
    "is_terminal_wait_stop_reason",
    "needs_attention_for_stop_reason",
    "normalize_usage",
    "normalize_subagent_profile_id",
    "normalize_subagent_scope_path",
    "normalize_subagent_tool_history",
    "normalize_subagent_tool_history_entry",
    "normalize_write_scope_paths",
    "resolve_subagent_profile",
    "should_auto_continue_run",
    "should_merge_subagent_workspace",
    "subagent_profile_allows_tool",
    "subagent_profile_schema_values",
    "validate_subagent_profile_scope",
    "write_scopes_overlap",
]
