"""rd-agent-core — host-neutral agent runtime kernel."""

from .business import (
    ArtifactDescriptor,
    ArtifactExtractorPort,
    ArtifactManifest,
    BusinessAgentAdapter,
    BusinessAgentProfile,
    BusinessTask,
    BusinessToolProviderPort,
    ContextProviderPort,
    PromptSection,
    VerificationPlan,
    VerificationPolicyPort,
)
from .conformance import (
    assert_event_log_port_conformance,
    assert_run_persistence_port_conformance,
    assert_tool_executor_port_conformance,
)
from .continuation_runner import (
    ContinuationRunner,
    ContinuationRunnerRequest,
    ContinuationRunnerResult,
)
from .continuation_state import ContinuationState, continuation_state_from_kernel_result
from .errors import CoreErrorCategory, CoreErrorType, classify_core_error, core_error
from .events import CoreEventType, CoreEventWriter
from .llm_clients import (
    AnthropicNativeLLMClient,
    OpenAICompatLLMClient,
    ProviderClientConfig,
)
from .model_profile import (
    ModelProfile,
    ReasoningEffort,
    model_profile_to_dict,
    normalize_model_profile,
)
from .observability import (
    AsyncRunObserverPort,
    RunObserverLike,
    RunObserverPort,
    notify_run_observer,
)
from .policies import (
    RunLimitDecision,
    RunLimits,
    RunLimitState,
    ToolCallSignature,
    ToolRepeatPolicy,
    evaluate_run_limits,
    has_repeated_tool_call,
    repeat_threshold_for_tool,
    tool_call_signature,
    tool_repeat_policy_from_metadata,
    would_exceed_repeat_threshold,
)
from .run import (
    RunKernel,
    RunKernelResult,
    RunRequest,
    build_messages_after_turn,
)
from .runner import AgentRunner, AgentRunnerRequest, AgentRunnerResult
from .subagent_runner import (
    SubagentBatchRunner,
    SubagentBatchRunnerError,
    SubagentBatchRunnerRequest,
    SubagentBatchRunnerResult,
    SubagentRunner,
    SubagentRunnerRequest,
    SubagentRunnerResult,
)
from .summary import RunSummary, summarize_failed_run, summarize_kernel_result
from .turn import (
    AsyncToolExecutorPort,
    CoreToolPolicy,
    LLMClientPort,
    ToolExecutorLike,
    ToolInputValidator,
    ToolOutputBlobWriter,
    ToolOutputLimiter,
    ToolSafetyPolicy,
    TurnKernel,
    TurnKernelResult,
    TurnRequest,
)

__version__ = "0.1.4"

__all__ = [
    "ArtifactDescriptor",
    "ArtifactExtractorPort",
    "ArtifactManifest",
    "AgentRunner",
    "AgentRunnerRequest",
    "AgentRunnerResult",
    "AnthropicNativeLLMClient",
    "AsyncRunObserverPort",
    "BusinessAgentAdapter",
    "BusinessAgentProfile",
    "BusinessTask",
    "BusinessToolProviderPort",
    "ContinuationRunner",
    "ContinuationRunnerRequest",
    "ContinuationRunnerResult",
    "ContinuationState",
    "ContextProviderPort",
    "AsyncToolExecutorPort",
    "CoreEventType",
    "CoreEventWriter",
    "CoreErrorCategory",
    "CoreErrorType",
    "CoreToolPolicy",
    "LLMClientPort",
    "ModelProfile",
    "OpenAICompatLLMClient",
    "PromptSection",
    "ProviderClientConfig",
    "ReasoningEffort",
    "RunLimitDecision",
    "RunKernel",
    "RunKernelResult",
    "RunLimitState",
    "RunLimits",
    "RunObserverLike",
    "RunObserverPort",
    "RunRequest",
    "RunSummary",
    "SubagentBatchRunner",
    "SubagentBatchRunnerError",
    "SubagentBatchRunnerRequest",
    "SubagentBatchRunnerResult",
    "SubagentRunner",
    "SubagentRunnerRequest",
    "SubagentRunnerResult",
    "ToolCallSignature",
    "ToolExecutorLike",
    "ToolOutputBlobWriter",
    "ToolInputValidator",
    "ToolOutputLimiter",
    "ToolRepeatPolicy",
    "ToolSafetyPolicy",
    "TurnKernel",
    "TurnKernelResult",
    "TurnRequest",
    "VerificationPlan",
    "VerificationPolicyPort",
    "assert_event_log_port_conformance",
    "assert_run_persistence_port_conformance",
    "assert_tool_executor_port_conformance",
    "build_messages_after_turn",
    "classify_core_error",
    "continuation_state_from_kernel_result",
    "core_error",
    "evaluate_run_limits",
    "has_repeated_tool_call",
    "model_profile_to_dict",
    "notify_run_observer",
    "normalize_model_profile",
    "repeat_threshold_for_tool",
    "summarize_failed_run",
    "summarize_kernel_result",
    "tool_call_signature",
    "tool_repeat_policy_from_metadata",
    "would_exceed_repeat_threshold",
]
